require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'Leeloo' do
  use_unimodules!(modules_paths: ['../node_modules'])
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
